version: '3.8'

services:
  moderator:
    build: .
    container_name: cnn_moderator
    ports:
      - "8001:8001"
    volumes:
      - ./weights:/app/weights
      - ./data:/app/data
    restart: always

# Elasticsearch service configuration
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: findway_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Set the initial and maximum heap size for Elasticsearch to 1 GB
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 2G # Limit Docker-container memory usage to 2 GB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data: